spring.application.name=projekt_medela_szymon

spring.datasource.url=jdbc:postgresql://localhost:5432/Projekt
spring.datasource.username=postgres
spring.datasource.password=GiQ6xghtW62ORi02
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb+srv://medelaszymon_db_user:mKZFtqw5DQ2LvyzU@data.sawohxk.mongodb.net/digital-activities?retryWrites=true&w=majority
