spring.application.name=projekt_medela_szymon

spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Projekt}
spring.datasource.username=${SPRING_DATABASE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATABASE_PASSWORD:GiQ6xghtW62ORi02}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.data.mongodb.uri=${SPRING_MONGODB_URI:mongodb+srv://medelaszymon_db_user:mKZFtqw5DQ2LvyzU@data.sawohxk.mongodb.net/digital-activities?retryWrites=true&w=majority}

# server.ssl.enabled=true
# server.port=8443
# server.ssl.key-store=classpath:tomcat_keystore.p12
# server.ssl.key-store-password=tomcat
# server.ssl.key-password=tomcat
# server.ssl.key-alias=servercert
# server.ssl.key-store-type=PKCS12

myparams.jdkversion=@java.version@
myparams.springbootversion=@parent.version@
application.name=@project.artifactId@
build.version=@project.version@
build.timestamp=@timestamp@

management.info.env.enabled=true
management.endpoints.web.exposure.include=info, health

info.contact.email=szymon.medela@o365.us.edu.pl
info.contact.phone=111-111-111
info.app.name=Projekt
info.app.description=Szymon Medela Grupa 2 Inzynieria Oprogramowania
info.app.version=1.0.0

server.port=${PORT:8080}

analysis.grpc.host=${ANALYSIS_GRPC_HOST:localhost}
analysis.grpc.port=${ANALYSIS_GRPC_PORT:50051}
analysis.gateway.base-url=${ANALYSIS_GATEWAY_BASE_URL:http://localhost:8080}